name: Mohnish's tidbits
description: 
meta_description: "Mohnish's tidbits"

markdown: redcarpet
pygments: true
logo: false
paginate: 25

# Details for the RSS feed generator
url:            'http://mohnish82.github.io'
author:         'Mohnish Chaudhary'
