title:        Mohnish's tidbits
tagline:      
description:  
url:          http://mohnish82.github.io
version:      1.1
author:
  name:       'Mohnish Chaudhary'
  email:      'mohnish82@gmail.com'
kramdown:     redcarpet
highlighter:  pygments
permalink:    pretty
pygments:     true
paginate:     5
